module Evergreen.Migrate.V13 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V13.Types
import Evergreen.V7.Types
import Lamdera.Migrations exposing (..)
import List


frontendModel : Evergreen.V7.Types.FrontendModel -> ModelMigration Evergreen.V13.Types.FrontendModel Evergreen.V13.Types.FrontendMsg
frontendModel old =
    ModelMigrated ( migrate_Types_FrontendModel old, Cmd.none )


backendModel : Evergreen.V7.Types.BackendModel -> ModelMigration Evergreen.V13.Types.BackendModel Evergreen.V13.Types.BackendMsg
backendModel old =
    ModelMigrated ( migrate_Types_BackendModel old, Cmd.none )


frontendMsg : Evergreen.V7.Types.FrontendMsg -> MsgMigration Evergreen.V13.Types.FrontendMsg Evergreen.V13.Types.FrontendMsg
frontendMsg old =
    MsgMigrated ( migrate_Types_FrontendMsg old, Cmd.none )


toBackend : Evergreen.V7.Types.ToBackend -> MsgMigration Evergreen.V13.Types.ToBackend Evergreen.V13.Types.BackendMsg
toBackend old =
    MsgMigrated ( migrate_Types_ToBackend old, Cmd.none )


backendMsg : Evergreen.V7.Types.BackendMsg -> MsgMigration Evergreen.V13.Types.BackendMsg Evergreen.V13.Types.BackendMsg
backendMsg old =
    MsgMigrated ( migrate_Types_BackendMsg old, Cmd.none )


toFrontend : Evergreen.V7.Types.ToFrontend -> MsgMigration Evergreen.V13.Types.ToFrontend Evergreen.V13.Types.FrontendMsg
toFrontend old =
    MsgMigrated ( migrate_Types_ToFrontend old, Cmd.none )


migrate_Types_BackendModel : Evergreen.V7.Types.BackendModel -> Evergreen.V13.Types.BackendModel
migrate_Types_BackendModel old =
    { message = old.message
    , kggames = old.kggames |> Dict.map (\k -> migrate_Types_KanjiGuessingGame)
    , players = old.players
    , seed = old.seed
    }


migrate_Types_FrontendModel : Evergreen.V7.Types.FrontendModel -> Evergreen.V13.Types.FrontendModel
migrate_Types_FrontendModel old =
    { key = old.key
    , message = old.message
    , kggames = old.kggames |> Dict.map (\k -> migrate_Types_KanjiGuessingGame)
    , username = old.username
    , thisPlayer = old.thisPlayer
    , currentlyPlaying = old.currentlyPlaying
    , players = old.players
    , kggWordInput = old.kggWordInput
    , kggWrongWordBuffer = old.kggWrongWordBuffer
    , kggConfigInputs =
        old.kggConfigInputs
            |> (\rec -> rec)
    , isEmbedded = old.isEmbedded
    , now = old.now
    , kanjidic = Dict.empty
    }


migrate_Types_BackendMsg : Evergreen.V7.Types.BackendMsg -> Evergreen.V13.Types.BackendMsg
migrate_Types_BackendMsg old =
    case old of
        Evergreen.V7.Types.ClientConnected p0 p1 ->
            Evergreen.V13.Types.ClientConnected p0 p1

        Evergreen.V7.Types.ClientDisconnected p0 p1 ->
            Evergreen.V13.Types.ClientDisconnected p0 p1

        Evergreen.V7.Types.GotJMdictSearchResults p0 p1 p2 ->
            Evergreen.V13.Types.GotJMdictSearchResults p0
                p1
                (p2 |> Result.map (List.map migrate_Types_JapDictEntry))

        Evergreen.V7.Types.GetKeys ->
            Evergreen.V13.Types.GetKeys

        Evergreen.V7.Types.GotKeys p0 ->
            Evergreen.V13.Types.GotKeys p0

        Evergreen.V7.Types.GotTime p0 ->
            Evergreen.V13.Types.GotTime p0

        Evergreen.V7.Types.RunGames p0 ->
            Evergreen.V13.Types.RunGames p0

        Evergreen.V7.Types.NoOpBackendMsg ->
            Evergreen.V13.Types.NoOpBackendMsg


migrate_Types_Ex_sent : Evergreen.V7.Types.Ex_sent -> Evergreen.V13.Types.Ex_sent
migrate_Types_Ex_sent old =
    case old of
        Evergreen.V7.Types.Ex_sent p0 p1 ->
            Evergreen.V13.Types.Ex_sent p0 p1


migrate_Types_Example : Evergreen.V7.Types.Example -> Evergreen.V13.Types.Example
migrate_Types_Example old =
    { ex_srce = old.ex_srce
    , ex_text = old.ex_text
    , ex_sent = old.ex_sent |> List.map migrate_Types_Ex_sent
    }


migrate_Types_FrontendMsg : Evergreen.V7.Types.FrontendMsg -> Evergreen.V13.Types.FrontendMsg
migrate_Types_FrontendMsg old =
    case old of
        Evergreen.V7.Types.UrlClicked p0 ->
            Evergreen.V13.Types.UrlClicked p0

        Evergreen.V7.Types.UrlChanged p0 ->
            Evergreen.V13.Types.UrlChanged p0

        Evergreen.V7.Types.GotInfoFromParent p0 ->
            Evergreen.V13.Types.GotInfoFromParent p0

        Evergreen.V7.Types.GotIFrameTestResult p0 ->
            Evergreen.V13.Types.GotIFrameTestResult p0

        Evergreen.V7.Types.UsernameInput p0 ->
            Evergreen.V13.Types.UsernameInput p0

        Evergreen.V7.Types.SendUser ->
            Evergreen.V13.Types.SendUser

        Evergreen.V7.Types.ReqGetKey ->
            Evergreen.V13.Types.ReqGetKey

        Evergreen.V7.Types.KggSetCustomKanjiSet p0 ->
            Evergreen.V13.Types.KggSetCustomKanjiSet 0 p0

        Evergreen.V7.Types.KggSetKanjiSet p0 p1 ->
            Evergreen.V13.Types.KggSetKanjiSet (p0 |> migrate_Types_KanjiSet)
                0

        Evergreen.V7.Types.KggStartGame p0 ->
            Evergreen.V13.Types.KggStartGame p0

        Evergreen.V7.Types.KggLoadInitialData p0 ->
            Evergreen.V13.Types.KggLoadInitialData p0

        Evergreen.V7.Types.KggWordInput p0 ->
            Evergreen.V13.Types.KggWordInput p0

        Evergreen.V7.Types.KggHostGame ->
            Evergreen.V13.Types.KggHostGame

        Evergreen.V7.Types.KggJoinGame p0 ->
            Evergreen.V13.Types.KggJoinGame p0

        Evergreen.V7.Types.KggLeaveGame p0 ->
            Evergreen.V13.Types.KggLeaveGame p0

        Evergreen.V7.Types.KggSendWord p0 ->
            Evergreen.V13.Types.KggSendWord p0

        Evergreen.V7.Types.KggRequestNextKanji p0 ->
            Evergreen.V13.Types.KggRequestNextKanji p0

        Evergreen.V7.Types.GotTimeF p0 ->
            Evergreen.V13.Types.GotTimeF p0

        Evergreen.V7.Types.SendToBackendWithTime p0 ->
            Evergreen.V13.Types.SendToBackendWithTime (p0 |> migrate_Types_ToBackend)

        Evergreen.V7.Types.KeyboardMsg p0 ->
            Evergreen.V13.Types.KeyboardMsg p0

        Evergreen.V7.Types.NoOpFrontendMsg ->
            Evergreen.V13.Types.NoOpFrontendMsg


migrate_Types_Gloss : Evergreen.V7.Types.Gloss -> Evergreen.V13.Types.Gloss
migrate_Types_Gloss old =
    case old of
        Evergreen.V7.Types.Gloss p0 p1 ->
            Evergreen.V13.Types.Gloss p0 p1


migrate_Types_JapDictEntry : Evergreen.V7.Types.JapDictEntry -> Evergreen.V13.Types.JapDictEntry
migrate_Types_JapDictEntry old =
    { ent_seq = old.ent_seq
    , k_ele = old.k_ele
    , r_ele = old.r_ele
    , sense = old.sense |> List.map migrate_Types_Sense
    , showingEverySense = old.showingEverySense
    }


migrate_Types_KGGameState : Evergreen.V7.Types.KGGameState -> Evergreen.V13.Types.KGGameState
migrate_Types_KGGameState old =
    case old of
        Evergreen.V7.Types.Lobby p0 ->
            Evergreen.V13.Types.Lobby
                { kanjiSet = p0.kanjiSet |> migrate_Types_KanjiSet
                , roundLength = p0.roundLength
                , startingCountdown = p0.startingCountdown
                , showingHints = False
                }

        Evergreen.V7.Types.Loading p0 ->
            Evergreen.V13.Types.Loading
                { initialBuffer =
                    p0.initialBuffer
                        |> (\rec1 -> rec1)
                , currentKanji = p0.currentKanji
                , remainingKanji = p0.remainingKanji
                , bufferedKanji = p0.bufferedKanji
                , allowedWords = p0.allowedWords
                , timeTillRoundEnd = p0.timeTillRoundEnd
                , timeTillGameOver = p0.timeTillGameOver
                , roundLength = p0.roundLength
                , startingCountdown = p0.startingCountdown
                , showingHints = False
                }

        Evergreen.V7.Types.InPlay p0 ->
            Evergreen.V13.Types.InPlay
                { score = p0.score
                , currentKanji = p0.currentKanji
                , remainingKanji = p0.remainingKanji
                , bufferedKanji = p0.bufferedKanji
                , kanjiSeen = p0.kanjiSeen
                , words = p0.words
                , allowedWords = p0.allowedWords
                , requestedSkip = p0.requestedSkip
                , timeTillRoundEnd = p0.timeTillRoundEnd
                , timeTillGameOver = p0.timeTillGameOver
                , roundLength = p0.roundLength
                , startingCountdown = p0.startingCountdown
                , showingHints = False
                }

        Evergreen.V7.Types.Victory p0 ->
            Evergreen.V13.Types.Victory
                { score = p0.score
                , words = Dict.empty
                }

        Evergreen.V7.Types.GameOver p0 ->
            Evergreen.V13.Types.GameOver
                { score = p0.score
                , words = Dict.empty
                }


migrate_Types_KanjiGuessingGame : Evergreen.V7.Types.KanjiGuessingGame -> Evergreen.V13.Types.KanjiGuessingGame
migrate_Types_KanjiGuessingGame old =
    { gameId = old.gameId
    , host = old.host |> migrate_Types_Player
    , players = old.players
    , gameState = old.gameState |> migrate_Types_KGGameState
    , lastUpdated = old.lastUpdated
    , buffering = old.buffering
    }


migrate_Types_KanjiSet : Evergreen.V7.Types.KanjiSet -> Evergreen.V13.Types.KanjiSet
migrate_Types_KanjiSet old =
    case old of
        Evergreen.V7.Types.JlptSet p0 ->
            Evergreen.V13.Types.JlptSet p0

        Evergreen.V7.Types.CustomKanjiSet p0 ->
            Evergreen.V13.Types.CustomKanjiSet p0


migrate_Types_LSource : Evergreen.V7.Types.LSource -> Evergreen.V13.Types.LSource
migrate_Types_LSource old =
    case old of
        Evergreen.V7.Types.LSource p0 p1 ->
            Evergreen.V13.Types.LSource p0 p1


migrate_Types_Player : Evergreen.V7.Types.Player -> Evergreen.V13.Types.Player
migrate_Types_Player old =
    old


migrate_Types_Sense : Evergreen.V7.Types.Sense -> Evergreen.V13.Types.Sense
migrate_Types_Sense old =
    { stagk = old.stagk
    , stagr = old.stagr
    , pos = old.pos
    , xref = old.xref
    , ant = old.ant
    , field = old.field
    , misc = old.misc
    , s_inf = old.s_inf
    , lsource = old.lsource |> List.map migrate_Types_LSource
    , dial = old.dial
    , gloss = old.gloss |> List.map migrate_Types_Gloss
    , example = old.example |> List.map migrate_Types_Example
    }


migrate_Types_ToBackend : Evergreen.V7.Types.ToBackend -> Evergreen.V13.Types.ToBackend
migrate_Types_ToBackend old =
    case old of
        Evergreen.V7.Types.GetKeysTB ->
            Evergreen.V13.Types.GetKeysTB

        Evergreen.V7.Types.PlayerInfoSubmittedTB p0 p1 ->
            Evergreen.V13.Types.PlayerInfoSubmittedTB p0 p1

        Evergreen.V7.Types.RequestInitialGamesBroadCastTB ->
            Evergreen.V13.Types.RequestInitialGamesBroadCastTB

        Evergreen.V7.Types.CreateGameTB p0 p1 p2 ->
            Evergreen.V13.Types.CreateGameTB (p0 |> migrate_Types_Player)
                { kanjiSet = Evergreen.V13.Types.JlptSet [ 5 ]
                , roundLength = 30
                , startingCountdown = 120
                , showingHints = False
                }
                p2

        Evergreen.V7.Types.JoinTB p0 p1 ->
            Evergreen.V13.Types.JoinTB (p0 |> migrate_Types_Player) p1

        Evergreen.V7.Types.LeaveTB p0 p1 ->
            Evergreen.V13.Types.LeaveTB (p0 |> migrate_Types_Player) p1

        Evergreen.V7.Types.UpdateConfigTB p0 p1 ->
            Evergreen.V13.Types.UpdateConfigTB p0
                { kanjiSet = Evergreen.V13.Types.JlptSet [ 5 ]
                , roundLength = 30
                , startingCountdown = 120
                , showingHints = False
                }

        Evergreen.V7.Types.LoadInitialDataTB p0 p1 ->
            Evergreen.V13.Types.LoadInitialDataTB p0 p1

        Evergreen.V7.Types.StartTB p0 p1 ->
            Evergreen.V13.Types.StartTB p0 p1

        Evergreen.V7.Types.RequestNextKanjiTB p0 p1 ->
            Evergreen.V13.Types.RequestNextKanjiTB p0 (p1 |> migrate_Types_Player)

        Evergreen.V7.Types.AddWordTB p0 p1 p2 ->
            Evergreen.V13.Types.AddWordTB p0 (p1 |> migrate_Types_Player) p2

        Evergreen.V7.Types.NoOpTB ->
            Evergreen.V13.Types.NoOpTB


migrate_Types_ToFrontend : Evergreen.V7.Types.ToFrontend -> Evergreen.V13.Types.ToFrontend
migrate_Types_ToFrontend old =
    case old of
        Evergreen.V7.Types.ToFrontendMsgTF p0 ->
            Evergreen.V13.Types.ToFrontendMsgTF p0

        Evergreen.V7.Types.GameBroadcastTF p0 ->
            Evergreen.V13.Types.GameBroadcastTF (p0 |> migrate_Types_KanjiGuessingGame)

        Evergreen.V7.Types.GameTimesBroadcastTF p0 ->
            Evergreen.V13.Types.GameTimesBroadcastTF p0

        Evergreen.V7.Types.WrongWordTF p0 ->
            Evergreen.V13.Types.WrongWordTF p0

        Evergreen.V7.Types.PlayerInfoRegisteredTF p0 ->
            Evergreen.V13.Types.PlayerInfoRegisteredTF (p0 |> migrate_Types_Player)

        Evergreen.V7.Types.NoOpTF ->
            Evergreen.V13.Types.NoOpTF
